import turtle
def ㅁ():
    for i in range(4):
        turtle.forward(100)
        turtle.left(90)
def ㅓ():
	turtle.left(90)
	ㄴ()
	turtle.left(180)
	turtle.forward(200)

def ㅜ():
	turtle.left(90)
	ㅓ()
def ㄴ():
	turtle.right(90)
	turtle.forward(70)
	turtle.left(90)
	turtle.forward(100)
def ㅈ():
	turtle.forward(100)
	turtle.right(140)
	turtle.forward(130)
	turtle.right(180)
	turtle.forward(70)
	turtle.right(90)
	turtle.forward(70)
def ㅕ():
	ㅓ()
	turtle.right(90)
	turtle.forward(70)
	turtle.right(180)
	ㅓ()
def ㅂ():
	ㄴ()
	turtle.right(180)
	ㄴ()
	ㄴ()
	turtle.undo()
	turtle.left(90)
	turtle.forward(70)
	turtle.left(90)
	ㄴ()
	turtle.left(90)
	turtle.forward(140)

def 문():
	ㅁ()
	turtle.penup()
	turtle.right(90)
	turtle.forward(100)
	turtle.left(90)
	turtle.forward(50)
	turtle.pendown()
	ㅜ()
	turtle.penup()
	turtle.left(180)
	turtle.forward(150)
	turtle.left(90)
	turtle.forward(30)
	turtle.left(90)
	turtle.pendown()
	ㄴ()
def 정():
        ㅈ()
        turtle.penup()
        turtle.right(180)
        turtle.forward(70)                
        turtle.right(130)
        turtle.forward(50)
        turtle.pendown()
        ㅓ()
        turtle.penup()
        turtle.right(90)
        turtle.forward(80)
        turtle.pendown()
        turtle.circle(50)
def 엽():    
        turtle.circle(60)
        turtle.penup()
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.pendown()
        ㅕ()
        turtle.penup()
        turtle.right(90)        
        turtle.forward(150)
        turtle.right(180)
        turtle.pendown()
        ㅂ()
        
turtle.penup()
turtle.goto(-500,200)
turtle.pendown()
문()
turtle.penup()
turtle.goto(-200,300)
turtle.pendown()
정()
turtle.penup()
turtle.right(180)
turtle.goto(200,200)
turtle.pendown()
엽()
        
turtle.exitonclick()
